#!/usr/bin/bash

fifofile=/tmp/dwmstatus
rm -rf ${fifofile}; mkfifo ${fifofile}


# W: weather
while true; do curl --silent 'http://weather.yahooapis.com/forecastrss?w=8676&u=c' | sed -ne '/Current Conditions/{n;p}' | sed -e 's/<BR \/>//' | xargs -r0 printf "W%s"; sleep 5; done > $fifofile &

# D: date
while true; do date '+D%b %d  %I:%M%p'; sleep 1; done > $fifofile &

# B: battery
while true; do acpi -b | awk '{gsub(",", ""); print $4}' | xargs -r0 printf "BB:%s"; sleep 2; done > $fifofile &

# C: cpu
while true; do awk 'BEGIN{i=0} {sum[i]=$2+$3+$4+$5; idle[i++]=$5} END {printf "CC:%d%%\n", 100*( (sum[1]-sum[0]) - (idle[1]-idle[0]) ) / (sum[1]-sum[0])}' \
    <( head -n1 /proc/stat; sleep 0.5; head -n1 /proc/stat); sleep 2; done > $fifofile &

# M: Memory
while true; do free -m | grep Mem | awk '{printf "MM:%0.1f%\n\r", ((($2 - $4)/$2)*100)}'; sleep 5; done > $fifofile &

# H: HDD - /
while true; do df -lh | awk '{if ($6 == "/") { print "HH:"$5 }}'; sleep 10; done > $fifofile &


weather="" clock="" battery="" cpu="" mem="" hdd="" sep="   "
cat ${fifofile} | while read -r line; do
    case "$line" in
        W*) weather="${line#?}${sep}";;
        D*) clock="${line#?}${sep}";;
        B*) battery="${line#?}${sep}";;
        C*) cpu="${line#?}${sep}";;
        M*) mem="${line#?}${sep}";;
        H*) hdd="${line#?}${sep}";;
    esac
    # TODO: hack preseve spaces for icons in systray of dwm
    status=$(echo "${weather}${cpu}${mem}${hdd}${clock}${battery}           " | sed "s/$sep$//")
    xsetroot -name "$status"
done
